source "https://rubygems.org"

#gem 'berkshelf',  '~> 2.0'
gem "rake"

group :test, :development do
  gem "chefspec", "~> 4.4.0" #, github: "sethvargo/chefspec", branch: "master"
end

group :development do
  # rubydeps currently breaks bundler installation
  #gem "rubydeps"
  gem "foodcritic", "~> 3.0"
  gem "rubocop"
  gem "jazz_fingers"
  gem "guard-rspec"
  gem "guard-bundler"
  # Prevent "Error: can't modify string; temporarily locked"
  # http://stackoverflow.com/a/19505033/179332
  gem "rb-readline", "~> 0.5.0"
end

